version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'weekly'
    ignore:
      # use to ignore types of semver major version updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      # Prefix all commit messages with "npm"
      prefix: 'npm'
    # Specify labels for npm pull requests
    labels:
      - 'security'
      - 'dependencies'
    # Allow up to 10 open pull requests for pip dependencies
    open-pull-requests-limit: 10