version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - '27018:27017'
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
volumes:
 mongodb:
 mongodb_config: