name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
          ports: '27018:27017'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clean install dependencies
        run: |
          npm ci
          npm run clean-install
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          # API runs on port 4000
          # Web server runs on port 3000
          start: npm run test:e2e:dev
          # wait for all services to respond
          wait-on: 'http://localhost:4000, http://localhost:27018'
