name: End-to-end tests

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [development]
    paths:
      - 'client/src/**'
      - 'server/src/**'
      - '!server/src/generated/**'

jobs:
  cypress-run:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: ['4.4']
    # Cypress Docker image with Chrome v100
    # and Firefox v98 pre-installed
    container: cypress/browsers:node14.17.6-chrome100-ff98
    
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Checkout
        uses: actions/checkout@v2

      # Starts a MongoDB server using custom port and credentials
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-port: 27018        
          mongodb-username: root
          mongodb-password: secret
          mongodb-db: grapevine-db
          mongodb-version: ${{ matrix.mongodb-version }}

      # Performs a clean installation of dependencies
      - run: npm ci
      - run: npm run clean-install
        
      # Runs all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          # we have already installed all dependencies above
          install: false
          # let's make sure our tests pass on Chrome browser
          browser: chrome
          # API runs on port 4000
          # Web server runs on port 3000
          start: npm run dev
          # wait for all services to respond
          wait-on: 'http://localhost:4000, http://localhost:3000'
          # overwrite the Cypress run command 
          # command: npm run cy:run
        # Environment variables used to connect to the database
        env:      
          AUTH_USER: root
          AUTH_PASS: secret
          DB_NAME: grapevine-db
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # uses the debug module to output additional verbose logs
          DEBUG: '@cypress/github-action'
