name: Build and Test

on:
  pull_request:
    branches: [development]
    paths:
      - '!client/src/**'
      - '!server/src/**'

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '
