name: 'CodeQL'
on:
  pull_request:
    branches: [development]
    paths:
      - 'client/src/**'
      - 'server/src/**'
      - '!server/src/generated/**'
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No analysis required" '