name: Build and Test

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '